# Generated by Django 3.0.5 on 2021-05-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.IntegerField(default=0)),
                ('identity', models.CharField(default='', max_length=240)),
                ('licence', models.CharField(default='', max_length=240)),
                ('matriculation', models.CharField(default='', max_length=240)),
                ('type', models.CharField(default='', max_length=240)),
                ('status', models.CharField(default='', max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField(default=0)),
                ('driver', models.IntegerField(default=0)),
                ('source', models.CharField(default='', max_length=240)),
                ('day', models.CharField(default='', max_length=240)),
                ('time', models.CharField(default='', max_length=240)),
                ('destination', models.CharField(default='', max_length=240)),
                ('status', models.CharField(default='', max_length=240)),
                ('destination_name', models.CharField(default='', max_length=240)),
                ('price', models.FloatField(default=0)),
                ('distance', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=240)),
                ('last_name', models.CharField(default='', max_length=240)),
                ('email', models.CharField(default='', max_length=240, unique=True)),
                ('phone_number', models.CharField(default='', max_length=240, unique=True)),
                ('address', models.CharField(default='', max_length=240)),
                ('identity_code', models.CharField(default='', max_length=240)),
                ('photo', models.CharField(default='', max_length=240)),
                ('password', models.CharField(default='', max_length=240)),
                ('rating', models.FloatField(default=0)),
                ('role', models.CharField(default='', max_length=240)),
            ],
        ),
    ]
